### PR TITLE
N.Y.T Clone review request

### PR DESCRIPTION
**Pull request by Mikearaya**
# we sincerely request your review  :smile:

### CODE REVIEW

**Comment by lekegitrepo** [comment]
### Hi @Mikearaya and @hatemswaileh 👏 👏 
### You did an exceptional job. The page looks great. However, you are still missing some minor requirements. Check my comments 👇 

**_1. The NY Times logo should be a link_** ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

**_2. Improve your pull request message it should contain more than "we sincerely request your review" instead it should contain what you did in your project._**

**_3. Improve the HTML semantic of your page by applying a basic structure: `<header></header> <main></main> <footer></footer>` the main should contain all the main contents of the page likewise use the footer for the footer contents and header for the header contents._**

**_4. Elements should be aligned with a combination of all three techniques_** ([float](https://css-tricks.com/all-about-floats/), [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) and [grid](https://css-tricks.com/snippets/css/complete-guide-grid/)). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_pathwright.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/)) and ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_odin.png) from [Odin](https://www.theodinproject.com/courses/html5-and-css3/lessons/positioning-and-floating-elements#introduction))

**_grid is missing in your style rules._**


### Optional:
**_1. Try to fix the screenshot image in your readme._**

**_2. Try to apply some margin or padding to the contents in More in Space and Astronomy section and Editor's Picks._**

**_If you have any doubts or questions contact me on slack._**

### Reviewed by: Temitayo Adeleke.

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
### Status: Require changes.

**Comment by Mikearaya** [comment]
Hi @lekegitrepo thank you for your quick response.
we appreciate your comments, we have fixed all the issues upon your request and added minor corrections of our own. 

Below you will find the issues that we fixed as your request, kindly check it and let us know if there is anything left.

### 1. Made the logo both at the top of the page and bottom links.
### 2. Adjusted semantics of the HTML file.
### 3. Converted the more section from flex to grid display
### 4. Fixed README.md screenshot image
### 5. Fixed margin at the more section of the page

Waiting for your feedback

**Comment by sumancrest0001** [comment]
Fantastic job TEAM :muscle: :muscle: :clap:
It looks very close to the original site. I find two minor things that need to be fixed to make it perfect. Trust me, It won't take much time. 
Please give some margin to **Editor's picks** section from the main section and remove the sticky nature of it which removed margin with the next section.
Screenshot from 2020-04-02 14-50-16
Screenshot from 2020-04-02 14-50-04

### in original, it looks like this. :point_down: :point_down:
Screenshot from 2020-04-02 14-51-57

**Comment by sumancrest0001** [comment]
Also, remove the scroll bar from the 
 **The Theory of Inflation** section. 
In your project 
Screenshot from 2020-04-02 14-54-50

**In the original site**

Screenshot from 2020-04-02 14-55-37


[OPTIONAL] Try to make the dimension of the main section similar to that of the original one. It seems narrower in your site.

Best of luck with the next submission. Inch closer to APPROVAL.
Need help? Reach out to me on slack **suman shrestha**

**Comment by hatemsweileh** [comment]
> Fantastic job TEAM 💪 💪 👏
> It looks very close to the original site. I find two minor things that need to be fixed to make it perfect. Trust me, It won't take much time.
> Please give some margin to **Editor's picks** section from the main section and remove the sticky nature of it which removed margin with the next section.
> Screenshot from 2020-04-02 14-50-16
> Screenshot from 2020-04-02 14-50-04
> 
> ### in original, it looks like this. 👇 👇
> Screenshot from 2020-04-02 14-51-57

I think we already did the margin but we made it responsive so I think your screen size is a little bit smaller than ours so you see it without margin or even the scroll bar, anyhow we just increased the iframe height and added an overflow for it.

and about the sticky part we know that the original website did not have it but we add it as an extra option I think we should be creative too, not just copy cat it.

Please view the image below to see the margin and space between the Editors' Picks Section and the main text area

Space Ripples Reveal Big Bang’s Smoking Gun - The New York Times

**Review by christianotieno — COMMENTED** [review]
## Pull Request under review by Christian Otieno (TSE)

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @Mikearaya & @hatemswaileh  :wave:
-
We are almost there! 🔢  The general layout looks good. And the earlier specified changes have been done. 🎆 
We, however, do have some few changes to carry out before we proceed (see review comment).
##

## [REQUIRED] - IMPLEMENT - The theory of inflation
While I was conducting the review, I noticed that you guys did not implement this section as it was required of you.
- This is usually the trickiest of parts with this project and it is where we learn the most implementing it with some grid and flex tricks. 😉 

I expected to see maybe, a background image of the icons with wordings floated to their exact places as is seen in the original.

Instead, this is what I was met with: 👇 

theory_of_inflation
An embedded HTML iframe. 
- I would kindly request for this section to be implemented. You are bound to learn so much from it.

## [REQUIRED] - ADD - Responsive support to smaller screens.
Your page seems not to be responsive in smaller screens, something you might have bypassed, unfortunately. 
- Kindly apply the your amazing skills to this and let's make our site responsive, shall we? 😄 Awesome 💪 

Please makes changes and submit another review request.
- If you have any questions, let me know here or on slack and I will be happy to assist. You can also reach me and connect with me on my social media or email. :eyes:

##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by Mikearaya** [comment]
as requested on the final code review we have changed the iframe for theory section to grid layout

**Review by MarioDena — CHANGES_REQUESTED** [review]
Hello good work on implementing the requested changes 👍 
However there are a few things that still need improvements.

## Required changes

- [x] Please remove the scrollbar from your table section and also fix the blank space on the right.
img
## Optional changes

- [x] There are bad practices on your CSS, like repeated rules (for example `display:flex` is repeated 17 times) You are also using ID for styling that is also a bad practice, You can read this article for more information: https://speckyboy.com/good-bad-css-practices/
[This change is OPTIONAL]

PLEASE NOTE THAT THIS OPTIONAL CHANGES WAS SUPPOSED TO BE MANDATORY, I'M ADDING IT AS OPTIONAL BECAUSE IT WAS NOT MENTIONED BEFORE, HOWEVER THIS IS MANDATORY ON EVERY PROJECT.

After making the requested changes please re-submit your project for review.

## Code Review by Mario Enrique Delgado Naranjo

**Comment by hatemsweileh** [comment]
Hello @MarioDena,
The thing is that we already did the issues that you pointed on, but the issue was in the demo link that we provide, it was taking cache from the old version, we changed a lot in the code and the website and it haven't been updated because of the cache, now we updated the demo link in the readme file now, and you can [view the new demo from here](https://rawcdn.githack.com/hatemswaileh/NYTClone-Mikael-Hatem/95fe64a7b3212337a4c6ca0ef755f180aedca1b5/index.html), thank you for your review

**Comment by Mikearaya** [comment]
-**removed x-axis scroll bar**
-**Increased width of theory section**

**Comment by sumancrest0001** [comment]
### [Approved] Congratulation TEAM :clap: :clap:  
Now you can merge your project and move ahead.
Happy coding :+1:

**Pull request merged**
